version: '3'

services:
  translate:
    build:
      context: ./translate
      dockerfile: ./Dockerfile
    ports:
      - "${TRANSLATE_HOST}:8000"
    expose:
      - "8000"
    container_name: fastapi-container
    restart: always

  back:
    build:
      context: "./back"
      dockerfile: "./Dockerfile"
    ports:
      - "${LINGUA_HOST}:8080" # Map the default port from the container to the host
    restart: always
    environment:
      TRANSLATE_HOST: ${TRANSLATE_DOCKER_HOST}
      SPRING_APPLICATION_JSON: |-
        {
          "spring": {
            "datasource": {
              "url": "jdbc:postgresql://db:5432/test",
              "username": "test",
              "password": "test"
            },
            "jpa": {
              "hibernate": {
                "ddl-auto": "update"
              },
              "show-sql": true
            }
          },
          "server": {
            "port": "8080"
          }
        }

  db:
    image: postgres:latest
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "${DATABASE_HOST}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
