version: '3'

services:
  back:
    build:
      context: "./back"
      dockerfile: "./Dockerfile"
    ports:
      - "0.0.0.0:8081:8080" # Map the default port from the container to the host
    restart: always
    environment:
      SPRING_APPLICATION_JSON: |-
        {
          "spring": {
            "datasource": {
              "url": "jdbc:postgresql://db:5432/test",
              "username": "test",
              "password": "test"
            },
            "jpa": {
              "hibernate": {
                "ddl-auto": "update"
              },
              "show-sql": true
            }
          },
          "server": {
            "port": "8080"
          }
        }

  db:
    image: postgres:latest
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "0.0.0.0:5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
