version: '3'

services:
  translate:
    build:
      context: ./translate
      dockerfile: ./Dockerfile
    ports:
      - "${TRANSLATE_HOST}:8000"
    expose:
      - "8000"
    container_name: fastapi-container
    restart: always

